<template>
	<div class="box">
		<div class="card-buttons-container">
			<div class="card-head">
				<portal-target :name="card.title"></portal-target>
				<!-- The Top Artists/Tracks toggle will be rendered here from the Toplist component -->
				<div class="right-card-content">
				<portal-target class="toplist-toggle" v-if="cardID == 'topArtists' || cardID == 'topTracks'" name="toplistToggle"></portal-target>
				<div class="buttons has-addons">
					<a v-if="card.buttons.includes('global')" @click="globalActive = !globalActive" 
						 class="button is-rounded is-small" :class="{'is-active':globalActive}"
					 >
						<font-awesome-icon icon="globe"></font-awesome-icon>
					</a>

					<a v-if="card.buttons.includes('about')" v-click-outside="closeTooltip" ref=about 
						v-tooltip="tooltip" @click="aboutActive=!aboutActive" class="button is-rounded is-small" 
						:class="{'is-active':aboutActive}"
					>
						<font-awesome-icon icon="question"></font-awesome-icon>
					</a>
				</div>
			</div>
			</div>
		</div>
		<slot :showGlobal="globalActive"></slot>
	</div>
</template>

<script>
export default {
	props: {
		cardID: null,
		toggle: false
	},
	data() {
		return {
			cards:{	
				"topArtists": {
					"title": "Top Artists",
					"aboutText": "Your top artists in three different time frames. The bar on the right indicates the global popularity of the artist. Note that this list is generated by Spotify themselves, changing the included sources will not have any effect.",
					"buttons": [
						"about"
					]
				},
				"uniqueness": {
					"title": "Uniqueness",
					"aboutText": "The higher the percentage, the more obscure are the songs you listen to. Based on the average popularity value of all tracks.",
					"buttons": [
						"about", "global"
					]
				},
				"topGenres": {
					"title": "Top Genres",
					"aboutText": "A list of your top genres. Keep in mind that genres are fetched from the artist of each track and not from the track itself.",
					"buttons": [
						"about","global"
					]
				},
				"playlistPopularity": {
					"title": "Most Unique Playlists",
					"aboutText":"A list of your most unique playlists. The bar on the right indicates the average popularity score for that playlist.",
					"buttons": [
						"about"
					]	       
				},
				"happinessRating": {
					"title": "Happiness",
					"aboutText": "The percentage of tracks considered to be happy or up-beat. (valence > 0.5)",
					"buttons": [
						"about","global"
					]
				},
				"topTracks": {
					"title": "Top Tracks",
					"aboutText": "Your top tracks in three different time frames. The bar on the right indicates the global popularity of the track. Note that this list is generated by Spotify themselves, changing the included sources will not have any effect.",
					"buttons": [
						"about"
					]
				},
				"comparePlaylists": {
					"title": "Playlist comparison",
					"aboutText": "Compare your playlists on different features. Most features are measured on a scale from 0-1.",
					"buttons": [
						"about"
					]
				},
				"moodOverTime": {
					"title": "Mood over time",
					"aboutText": "The average happiness for tracks added to playlists during the interval between every data point. Note that the x-axis is scaled so that the amount of tracks between every point is evenly distributed.",
					"buttons": [
						"about"
					]
				},
				"yearOfRelease": {
					"title": "Release Dates",
					"aboutText": "A chart showing, for each year, the percentage of tracks released that year. Release dates are fetched from each track's album.",
					"buttons": [
						"about", "global"
					]
				},
				"explicitTracks": {
					"title": "Explicit tracks",
					"aboutText": "The percentage of tracks containing explicit lyrics.",
					"buttons": [
						"about","global"
					]
				},
				"playlists": {
					"title": "Playlist Quick Facts",
					"aboutText": "Playlist specific charts including top genres, average features and release dates.",
					"buttons": [
						"about"
					]
				}
			},
			aboutActive: false,
			globalActive: false
		}
	},
	computed: {
		card() {
			return this.cards[this.cardID]
		},
		tooltip() {
			return {
				content: this.card.aboutText,
				trigger: 'manual',
				show: this.aboutActive,
				placement: 'bottom-end',
				autoHide: true
			}
		}
	},
	methods: {
		closeTooltip: function() {
			this.aboutActive = false;
		}
	},
	watch: {
		aboutActive() {
			if (this.aboutActive) {
				this.$analytics.logEvent('clicked_about',{card:this.cardID});
			}
		},
		globalActive() {
			if (this.globalActive) {
				this.$analytics.logEvent('clicked_global',{card:this.cardID});
			}
		}
	}
};
</script>

<style lang="scss">
@import '../theme.sass';
.card-buttons-container {
	display: flex;
	flex-flow: column;
	padding: 0;
}
.card-head {
	display: flex;
	flex-flow: row;
	width: 100%;
	align-items: center !important;
	margin-top: 0.25em;
	margin-bottom: 0.25em;
}
.card-head .card-title { 
	text-align: left !important;
	font-weight: bold !important;
	font-size: 1.5em !important;
	color: $title-color !important;
}
.buttons > .is-active {
	color:#BF61B0 !important;
}

.right-card-content {
	align-self: flex-start;
	margin-left: auto;
	display: flex;
}

.toplist-toggle {
	margin-right: 0.25em;
}

/* Tooltip */
.tooltip {
	display: block !important;
	z-index: 10000;
}
.box {
	padding-top: 2px !important;
	text-align: center;
	padding-right: 5px !important;
	padding-left: 5px !important;
}
@media screen and (max-width: 600px) { /* Prevents horizontal overflow */
	.tooltip {
		margin-right: 0.5em;
	}
}

.tooltip .tooltip-inner {
	background: black;
	color: white;
	max-width:350px;
	border-radius: 16px;
	font-size:0.9em;
	padding: 5px 10px 4px;
}

.tooltip .tooltip-arrow {
	width: 0;
	height: 0;
	border-style: solid;
	position: absolute;
	margin: 5px;
	border-color: black;
	z-index: 1;
}

.tooltip[x-placement^="top"] {
	margin-bottom: 5px;
}

.tooltip[x-placement^="top"] .tooltip-arrow {
	border-width: 5px 5px 0 5px;
	border-left-color: transparent !important;
	border-right-color: transparent !important;
	border-bottom-color: transparent !important;
	bottom: -5px;
	left: calc(50% - 5px);
	margin-top: 0;
	margin-bottom: 0;
}

.tooltip[x-placement^="bottom"] {
	margin-top: 5px;
}

.tooltip[x-placement^="bottom"] .tooltip-arrow {
	border-width: 0 5px 5px 5px;
	border-left-color: transparent !important;
	border-right-color: transparent !important;
	border-top-color: transparent !important;
	top: -5px;
	left: calc(50% - 5px);
	margin-top: 0;
	margin-bottom: 0;
}

.tooltip[x-placement^="right"] {
	margin-left: 5px;
}

.tooltip[x-placement^="right"] .tooltip-arrow {
	border-width: 5px 5px 5px 0;
	border-left-color: transparent !important;
	border-top-color: transparent !important;
	border-bottom-color: transparent !important;
	left: -5px;
	top: calc(50% - 5px);
	margin-left: 0;
	margin-right: 0;
}

.tooltip[x-placement^="left"] {
	margin-right: 5px;
}

.tooltip[x-placement^="left"] .tooltip-arrow {
	border-width: 5px 0 5px 5px;
	border-top-color: transparent !important;
	border-right-color: transparent !important;
	border-bottom-color: transparent !important;
	right: -5px;
	top: calc(50% - 5px);
	margin-left: 0;
	margin-right: 0;
}

.tooltip.popover .popover-inner {
	background: #f9f9f9;
	color: black;
	padding: 24px;
	border-radius: 5px;
	box-shadow: 0 5px 30px rgba(black, .1);
}

.tooltip.popover .popover-arrow {
	border-color: #f9f9f9;
}

.tooltip[aria-hidden='true'] {
	visibility: hidden;
	opacity: 0;
	transition: opacity .15s, visibility .15s;
}

.tooltip[aria-hidden='false'] {
	visibility: visible;
	opacity: 1;
	transition: opacity .15s;
}

</style>
